name: Broken Links Checker
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
env:
  ISSUE_TEMPLATE: ".github/workflows/ISSUE_TEMPLATE.md"

  contents: read
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get links from README.md
        id: get-links
        run: |
          LINKS=$(sed -nE 's/\[.*\]\((http[s]?:\/\/[^)]*)\)/\1/p' README.md | paste -sd ,)
          echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
      - name: Run Broken Links Checker
        run: |
          # Split the list of links into an array separated by commas
          read -ra LINKS <<< $WEBSITE_URL
          BROKEN_LINKS=()
          
          # Scan the links and verify if they are reachable
          for link in "${LINKS[@]}"; do
              if ! curl -IsSk "$link" > /dev/null; then
                BROKEN_LINKS+=("$link")
              fi
          done
          
          if [ ${#BROKEN_LINKS[@]} -gt 0 ]; then
           echo "Broken links found: ${BROKEN_LINKS[@]}" >&2
           echo "Broken links found, failing the workflow" >&2
           exit 1
          else
           echo "No broken links found"
          fi
          # Converti l'array in una stringa separata da virgole
           BROKEN_LINKS_STRING=$(IFS=','; echo "${BROKEN_LINKS[*]}")
   
          # Passa la stringa come variabile d'ambiente
           echo "BROKEN_LINKS=$BROKEN_LINKS_STRING" >> $GITHUB_ENV

      - name: Create Issue for Broken Links
        if: failure()
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d "{\"title\":\"Broken Links Found\",\"body\":\"Broken links found: ${BROKEN_LINKS[@]}\"}"