name: Broken Links Checker
on: 
  [push]
env:
  ISSUE_TEMPLATE: ".github/workflows/ISSUE_TEMPLATE.md"
 
  contents: read
  issues: write 
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get links from README.md
      id: get-links
      run: |
       LINKS=$(sed -nE 's/\[.*\]\((http[s]?:\/\/[^)]*)\)/\1/p' README.md | paste -sd ,)
       echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
      
    - name: Run Broken Links Checker
      run: |
        # Split the list of links into an array separated by commas
        read -ra LINKS <<< "$WEBSITE_URL"
        BROKEN_LINKS=()

        # Scan the links and verify if they are reachable
        for link in "${LINKS[@]}"; do
          if [[ $link =~ ^(http|https):// ]]; then
            # Scan the links and verify if they are reachable
            if ! curl -IsSk "$link" > /dev/null; then
              BROKEN_LINKS+=("$link")
            fi
          fi
        done

        if [ ${#BROKEN_LINKS[@]} -gt 0 ]; then
          echo "Broken links found: ${BROKEN_LINKS[@]}" >&2
          BROKEN_LINKS_STRING=$(echo "${BROKEN_LINKS[@]}" | tr '\n' ';')
          echo "BROKEN_LINKS=$BROKEN_LINKS_STRING" >> $GITHUB_ENV
          echo "Broken links found:  ${BROKEN_LINKS[@]}"
          echo "Broken links found, failing the workflow"
          ISSUE_NAME="Sites Containing Broken Links"  # Sostituisci con il nome dell'issue che vuoi verificare
          ISSUE_NUMBER=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/issues?q=$ISSUE_NAME" | jq -r '.items[0].number')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
          ISSUE_LINKS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER" | jq -r '.body' | grep -oP '(?<=\()[^\)]+' | paste -sd ,)
          if [ "$ISSUE_LINKS" == "$BROKEN_LINKS" ]; then
           echo "Links in issue #$ISSUE_NUMBER match the links in README.md"
          else
          exit 1
        else
          echo "No broken links found"
        fi

     

    - uses: actions/checkout@v3
      if: failure()

    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()







